// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBlogPosts = `-- name: CountBlogPosts :one
SELECT count(*) FROM blog_posts
`

func (q *Queries) CountBlogPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlogPostsByBundlePath = `-- name: DeleteBlogPostsByBundlePath :execresult
DELETE FROM blog_posts WHERE path LIKE $1 || '?%'
`

func (q *Queries) DeleteBlogPostsByBundlePath(ctx context.Context, dollar_1 pgtype.Text) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteBlogPostsByBundlePath, dollar_1)
}

const getBlogPostByPostUrl = `-- name: GetBlogPostByPostUrl :one
SELECT blog_platform, post_url, path, published_at, created_at, updated_at
FROM blog_posts
WHERE post_url = $1
`

func (q *Queries) GetBlogPostByPostUrl(ctx context.Context, postUrl string) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostByPostUrl, postUrl)
	var i BlogPost
	err := row.Scan(
		&i.BlogPlatform,
		&i.PostUrl,
		&i.Path,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT blog_platform, post_url, path, published_at, created_at, updated_at
FROM blog_posts
WHERE ($2::text IS NULL OR path > $2::text)
ORDER BY path
LIMIT $1
`

type ListBlogPostsParams struct {
	Limit  int32       `json:"limit"`
	Cursor pgtype.Text `json:"cursor"`
}

func (q *Queries) ListBlogPosts(ctx context.Context, arg ListBlogPostsParams) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogPosts, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.BlogPlatform,
			&i.PostUrl,
			&i.Path,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlogPost = `-- name: UpsertBlogPost :exec
INSERT INTO blog_posts (blog_platform, post_url, path, published_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (post_url) DO UPDATE SET
    path = EXCLUDED.path,
    published_at = EXCLUDED.published_at,
    updated_at = current_timestamp
`

type UpsertBlogPostParams struct {
	BlogPlatform string           `json:"blog_platform"`
	PostUrl      string           `json:"post_url"`
	Path         string           `json:"path"`
	PublishedAt  pgtype.Timestamp `json:"published_at"`
}

func (q *Queries) UpsertBlogPost(ctx context.Context, arg UpsertBlogPostParams) error {
	_, err := q.db.Exec(ctx, upsertBlogPost,
		arg.BlogPlatform,
		arg.PostUrl,
		arg.Path,
		arg.PublishedAt,
	)
	return err
}
